config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  resources :pages, only: [:home, :index, :new, :create]

  devise_for :users, path: '',
                     path_names: { sign_up: 'insciption', sign_in: 'connexion', sign_out: 'déconnexion', edit: 'profil' },
                     controllers: { registrations: 'registrations',
                                    confirmations: 'confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: %i[show index destroy] do
    match :search, to: 'users#index', via: :post, on: :collection
  end

  resources :annonces do
    resources :negoces, only: %i[create]
    resources :reviews, only: %i[create destroy]
  end

  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/partenariats' => 'negoces#your_partnerships'
  get '/propositions' => 'negoces#your_negoces'
end

app/models/negoce.rb
class Negoce < ApplicationRecord
  belongs_to :user
  belongs_to :annonce
end

app/controllers/negoces_controller.rb
class NegocesController < ApplicationController
  before_action :authenticate_user!

  def create
    @negoce = current_user.negoces.create(negoce_params)
    redirect_to @negoce.annonce, notice: 'Votre demande de partenariat a été envoyée'
  end

  def your_partnerships
    @partnerships = current_user.negoces
  end

  def your_negoces
    @annonces = current_user.annonces
  end

  private

  def negoce_params
    params.require(:negoce).permit(:price, :total, :annonce_id, :quantite_ask)
  end
end

app/views/negoces/_form.html.erb
<%= form_for([@annonce, @annonce.negoces.new]) do |f| %>     
   
<div class="row">
	<div class="col-md-12 price_tag">
		<span>€ <%= @annonce.price %></span>
		<span class="pull-right"><%= @annonce.product %></span>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<label>Quantité demandée</label>
		<%= f.text_field :quantite_ask, placeholder: 'quantité', class: 'form-control' %>
	</div>
</div>

<div id="preview" style="display: none">
	<table class="negoce-table" >
		<tbody>
			<tr>
				<td>Quantitée demandée</td>
				<td><span id="negoce_quantité_ask"></span></td>
			</tr>
			
			<tr>
				<td>Total</td>
				<td><span id="negoce_sum"></span>€</td>
			</tr>
		</tbody>
	</table>
</div>

<%= f.hidden_field :annonce_id, value: @annonce.id %>
<%= f.hidden_field :price, value: @annonce.price %>
<%= f.hidden_field :total, id: 'negoce_total' %>

<br>

<%= f.submit "Demande de partenariat ", class: "btn btn-primary wide" %>

<% end %>

app/views/negoces/your_negoces.html.erb
  <div class="row">
    <div class="col-md-3">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "Mes annonces", annonces_path, class:"sidebar-link" %></li>
        <li class="sidebar-item"><%= link_to "Mes propositions de partenariat", propositions_path, class:"sidebar-link active" %></li>
        <li class="sidebar-item"><%= link_to "Mes partenariats", partenariats_path, class:"sidebar-link" %></li>
      </ul>
    </div>
  
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Mes propositions de partenariat</div>
        <div class="panel-body">
          
          <% @annonces.each do |annonce| %>
            
            <% annonce.negoces.order("id DESC").each do |negoce| %>
              
              <div class="row">
                <div class="col-md-2">
                  quantitée demandée: <%= negoce.quantite_ask %>
                </div>
                
                <div class="col-md-6">
                  <%= link_to annonce_path(negoce.annonce) do %>
                    <%= image_tag negoce.annonce.photos[0].image.url(:thumb) if negoce.annonce.photos.length > 0 %>
                  <% end %>
                </div>
                
                <div class="col-md-2">
                  <%= link_to user_path(negoce.annonce.user) do %>
                    <%= image_tag avatar_url(negoce.user), class:"img-circle avatar-medium" %>
                  <% end %>
                </div>
                
                <div class="col-md-2 right">
                  <h4><%= negoce.total %> €</h4>
                </div>
              </div>
              
              <hr>
            
            <% end %>
          
          <% end %>
        
        </div>
      </div>
    </div>
  </div>

app/views/negoces/your_partnerships.html.erb
  <div class="row">
    <div class="col-md-3">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "Mes annonces", annonces_path, class:"sidebar-link" %></li>
        <li class="sidebar-item"><%= link_to "Mes propositions de partenariat", propositions_path, class:"sidebar-link" %></li>
        <li class="sidebar-item"><%= link_to "Mes partenariats", partenariats_path, class:"sidebar-link active" %></li>
      </ul>
    </div>
  
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Mes partenariats</div>
      
        <div class="panel-body">
        
          <% @partnerships.order("id DESC").each do |partnership| %>
          
            <div class="row">
              <div class="col-md-2">
                quantitée demandée: <%= partnership.quantite_ask %>
              </div>
            
              <div class="col-md-6">
                <%= link_to annonce_path(partnership.annonce) do %>
                  <%= image_tag partnership.annonce.photos[0].image.url(:thumb) if partnership.annonce.photos.length > 0 %>
                <% end %>
              </div>
            
              <div class="col-md-2">
                <%= link_to user_path(partnership.annonce.user) do %>
                  <%= image_tag avatar_url(partnership.annonce.user), class:"img-circle avatar-medium" %>
                <% end %>
              </div>
            
              <div class="col-md-2 right">
                <h4><%= partnership.total %> €</h4>
              </div>
            </div>
          
            <hr>
        
          <% end %>
      
        </div>
      </div>
    </div>
  </div>