config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  resources :pages, only: [:home, :index, :new, :create]

  devise_for :users, path: '',
                     path_names: { sign_up: 'insciption', sign_in: 'connexion', sign_out: 'déconnexion', edit: 'profil' },
                     controllers: { registrations: 'registrations',
                                    confirmations: 'confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: %i[show index destroy] do
    match :search, to: 'users#index', via: :post, on: :collection
  end

  resources :annonces do
    resources :negoces, only: %i[create]
    resources :reviews, only: %i[create destroy]
  end

  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/partenariats' => 'negoces#your_partnerships'
  get '/propositions' => 'negoces#your_negoces'
end

app/models/annonce.rb
class Annonce < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :negoces
  has_many :reviews

  validates :product, presence: true
  validates :product_name, presence: true, length: { maximum: 75 }
  validates :product_type, presence: true
  validates :description_annonce, presence: true, length: { maximum: 600 }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @annonces = current_user.annonces

    @search = User.ransack params[:q]
    @users = @search.result
  end

  def new
    @annonce = current_user.annonces.build
  end

  def create
    @annonce = current_user.annonces.build(annonce_params)
    if @annonce.save
      if params[:images]
        params[:images].each do |i|
          @annonce.photos.create(image: i)
        end
      end
      @photos = @annonce.photos
      redirect_to annonce_path(@annonce), notice: 'Votre annonce a été ajouté avec succès'
    else
      render :new
    end
  end

  def show
    @photos = @annonce.photos

    @reviews = @annonce.reviews
    if current_user
      # ATTENTION : changer @booked
      # @booked = Negoce.where("annonce_id = ? AND user_id = ?", @annonce.id, current_user.id).present?
      @hasReview = @reviews.find_by(user_id: current_user.id)
    end
  end

  def edit
    @photos = @annonce.photos
  end

  def update
    if @annonce.update(annonce_params)
      if params[:images]
        params[:images].each do |i|
        @annonce.photos.create(image: i)
      end
    end
      @annonce.save
      redirect_to annonce_path(@annonce), notice: 'Modification enregistrée...'
    else
      render :edit
    end
  end

  def destroy
    @annonce.destroy
      if params[:images]
        params[:images].each do |i|
        @annonce.photos.destroy(image:i)
      end
    end
    redirect_to annonces_path, notice: "votre annonce à été suprimmée avec succés "
  end


  private

  def set_annonce
    @annonce = Annonce.find(params[:id])
  end

  def annonce_params
    params.require(:annonce).permit(:product, :product_name, :product_type,
                                    :description_annonce, :price, :quantite, :active)
  end

  def require_same_user
    if current_user.id != @annonce.user_id
      flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
      redirect_to root_path
    end
  end
end

app/views/annonces/_form.html.erb
    <div class="panel panel-default">
        <div class="panel-heading">
            Créer vos fiches produit ou service
        </div>

        <div class="panel-body">
            <div class="container">

                <%= form_for @annonce, html: {multipart: true} do |f| %>
                    <%= render 'shared/errors' %>

                    <div class="row">
                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Produit ou service</label>
                                <%= f.select :product, [["Produit","Produit"], ["Service","Service"]], id: "product", 
                                prompt: "A sélectionner...", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label>Le secteur de marché de votre produit.</label>
                            <%= f.text_field :product_type, placeholder: "Le type de produit ou service", class: "form-control" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label>le nom du produit ou service</label>
                            <%= f.text_field :product_name, placeholder: "Titre du produit ou service", class: "form-control" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <span class="btn btn-default btn-file">
                                    <i class = "fa fa-cloud-upload-alt fa-lg"></i> Téléchargez des photos de vos produits et/ou services!
                                    <%= file_field_tag "images[]", type: :file, multiple: true %>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div id="photos"><%= render 'photos/list' %></div>

                    <div class="row">
                        <div class="form-group">
                            <label>description de votre produit/service, votre offre, les avantages, etc,...</label>
                            <%= f.text_area :description_annonce, rows:4, placeholder: "Décrivez le produit ou service, son utilité, ses avantages, etc...",
                            class: "form-control" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label>La quantité disponible</label>
                            <%= f.text_field :quantite, placeholder: "ex: 25", class: "form-control" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Prix par unité</label>
                                <div class="input-group">
                                    <%= f.text_field :price, placeholder: "ex: 45€", class: "form-control" %>
                                    <div class="input-group-addon">€</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- <div class="row">
                        <div class="form-group">
                            f.check_box :active Vente active
                        </div>
                    </div> -->

                    <div class="actions">
                        <%= f.submit "Je valide", class: "btn btn-primary" %>
                    </div>

                <% end %>

            </div>
        </div>
    </div>

app/views/annonces/edit.html.erb
<%= render 'form' %>

app/views/annonces/index.html.erb
    <div class="row">
        <div class="col-md-3">
            <ul class="sidebar-list">
                <li class="sidebar-item">
                    <%= link_to "Mes annonces", annonces_path, class:"sidebar-link" %>
                </li>

                <li class="sidebar-item">
                    <%= link_to "Mes propositions de partenariat", propositions_path, class:"sidebar-link" %>
                </li>

                <li class="sidebar-item">
                    <%= link_to "Mes partenariats", partenariats_path, class:"sidebar-link" %>
                </li>
            </ul>
        </div>

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Mes annonces</div>
                <div class="panel-body">

                    <% @annonces.each do |annonce| %>

                        <div class="row">
                            <div class="col-md-2">
                                <%= annonce.product %>:
                                <%= image_tag annonce.photos[0].image.url(:thumb) if annonce.photos.length > 0 %>
                            </div>

                            <div class="col-md-7">
                                <h4>Nom du <%= annonce.product %>: <strong><%= annonce.product_name %></strong></h4> <br>
                                Type du <%= annonce.product %>: <%= annonce.product_type %>
                            </div>

                            <div class="col-md-3 right">
                                <%= link_to "Mettre à jour", edit_annonce_path(annonce), class: "btn btn-primary" %>
                            </div>

                            <div class="col-md-3 right">
                                <br>
                                <%= link_to "Voir mon annonce", annonce_path(annonce), class: "btn btn-primary" %>
                            </div>
                            
                            <div class="col-md-3 right">
                                <br>
                            <%= link_to 'Supprimer mon annonce', annonce_path(annonce), method: :delete, data: {confirm: 'ëtes-vous sur de vouloir supprimer votre annonce?'}, class: "btn btn-primary" %>
                            </div>
                        </div>

                        <hr>

                    <% end %>

                </div>
            </div>
        </div>
    </div>

app/views/annonces/new.html.erb
<%= render 'form' %>

app/views/annonces/show.html.erb
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-3 text-center">
                            <%= link_to user_path(@annonce.user) do %>
                                <%= image_tag avatar_url(@annonce.user), class:"img-circle avatar-large" %>
                            <% end %>

                            <br>

                            <%= link_to user_path(@annonce.user) do %>
                                Entreprise: <%= @annonce.user.firm_name %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

            <br>

            <!-- Carousel -->
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <% if @photos %>
                            <% @photos.each do |photo| %>
                                <ol class="carousel-indicators">
                                    <li data-target="#myCarousel" data-slide-to="<%= photo.id %>" class="active"></li>
                                </ol>
                            <% end %>
                        <% end %>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <% if @photos %>
                                <% @photos.each do |photo| %>
                                    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                                        <%= image_tag photo.image.url() %>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>

                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Précédent</span>
                        </a>

                        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Suivant</span>
                        </a>
                    </div>
                </div>
            </div>

            <br>
            <hr>

            <!-- Informations principales -->
            <div class="row">
                <div class="col-md-12"></div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-9">
                            <a href="#average_rating", class="sidebar-link"><span id="average_rating_header"></span> <%= @reviews.count %></a>
                            <h2>A propos de ce <%= @annonce.product %></h2>
                            <p><%= @annonce.description_annonce %></p>
                            <%= @annonce.product_name %> 
                            <%= @annonce.product_type %>
                            <br>
                            <br>
                            <span class="<%= 'text-hidden' if @annonce.quantite.nil? %>">
                                La quantité disponible est de <%= @annonce.quantite %>
                                <br>
                            </span>
                            Le prix est de <%= @annonce.price %>€
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <!-- Formulaire de réservation -->
                    <%= render 'negoces/form' %>
                </div>
            </div>
            
            <br>
            <br>
            <br>
        
            <!-- Reviews -->
            <div class="row">
                <div class="col-md-12">
                    <h3><%= pluralize(@reviews.count, 'commentaire') %></h3>
                    <div class="container">
                        <%= render 'reviews/form' if !@hasReview %>
                        <!-- ATTENTION : @booked à changer ou supprimer -->
                        <!-- render 'reviews/form' if @booked && !@hasReview -->
                    </div>
                    <%= render 'reviews/list' %>
                </div>
            </div>
        </div>
    </div>

<script>
    $('#average_rating').raty({
        path: '/assets',
        readOnly: true,
        score: <%= @annonce.average_rating %>
    });
</script>

<script>
    $('#average_rating_header').raty({
        path: '/assets',
        readOnly: true,
        score: <%= @annonce.average_rating %>
    });
</script>