config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  resources :pages, only: [:home, :index, :new, :create]

  devise_for :users, path: '',
                     path_names: { sign_up: 'insciption', sign_in: 'connexion', sign_out: 'déconnexion', edit: 'profil' },
                     controllers: { registrations: 'registrations',
                                    confirmations: 'confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: %i[show index destroy] do
    match :search, to: 'users#index', via: :post, on: :collection
  end

  resources :annonces do
    resources :negoces, only: %i[create]
    resources :reviews, only: %i[create destroy]
  end

  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/partenariats' => 'negoces#your_partnerships'
  get '/propositions' => 'negoces#your_negoces'
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small blue pt-4 mt-4">
    <div class="container-fluid text-md-left">
        <div class="row">
            <div class="col-md-6">
                <p>Mail: <strong>contact@startme-up.com</strong></p>
                <p>Tél: <strong>07 64 00 91 40</strong></p>
            </div>        
        </div>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="Sales&Buy" class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
      <%= link_to 'Sales&Buy', root_path, { :class=>"navbar-brand" } %>
    </div>
    
    <div id="myNavbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <li>
          <%= link_to "Recherche", users_path, style: "color: #1E90FF; font-weight: bold;" %>
        </li>

        <li>
          <%= link_to conversations_path do %>
            <i class="far fa-envelope fa-lg"></i> Boîte de réception
          <% end %>
        </li>

        <li>
          <%= link_to new_annonce_path do %>
            <i class="far fa-money-bill-alt fa-lg"></i> Créer vos annonces
          <% end %>
        </li>
        
        <% if (!user_signed_in?) %>
          
          <li>
            <%= link_to 'Inscription', new_user_registration_path %>
          </li>
          
          <li>
            <%= link_to 'Connexion', new_user_session_path %>
          </li>
        
        <% else %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %>
              <%= current_user.firm_name %>
              <span class="caret"></span>
            </a>
            
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Mes annonces", annonces_path %>
              </li>
              
              <li>
                <%= link_to "Mes propositions de partenariat", propositions_path %>
              </li>
              
              <li>
                <%= link_to "Mes partenrariats", partenariats_path %>
              </li>

              <li>
                <%= link_to "Boîte de réception", conversations_path  %>
              </li>
              
              <li role="separator" class="divider"></li>
              
              <li>
                <%= link_to 'Voir mon profil', user_path(current_user.id) %>
              </li>
              
              <li>
                <%= link_to 'Modifier mon profil', edit_user_registration_path %>
              </li>
              
              <li>
                <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      
      </ul>
    </div><!--/.nav-collapse -->
  
  </div>
</nav>

<style>
  /* navbar responsive */
  @media (max-width: 1060px) {
    .navbar-header {
      float: none;
    }
    .navbar-left,.navbar-right {
      float: none !important;
    }
    .navbar-toggle {
      display: block;
    }
    .navbar-collapse {
      border-top: 1px solid transparent;
      box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
    }
    .navbar-fixed-top {
		  top: 0;
		  border-width: 0 0 1px;
	  }
    .navbar-collapse.collapse {
      display: none!important;
    }
    .navbar-nav {
      float: none!important;
		  margin-top: 7.5px;
	  }
	  .navbar-nav>li {
      float: none;
    }
    .navbar-nav>li>a {
      padding-top: 10px;
      padding-bottom: 10px;
    }
    .collapse.in{
  		display:block !important;
	  }
  }
  /* navbar css */
  .navbar {
    background-color: #fff;
    z-index: 9999;
    font-size: 12px !important;
    line-height: 1.42857143 !important;
    letter-spacing: 4px;
    border-radius: 0;
    font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
    color: rgb(30, 40, 150) !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
    color: #fff !important;
    background-color: rgb(30, 40, 150) !important;
  }
  .navbar-default .navbar-toggle {
    border-color: transparent;
    color: rgb(30, 40, 150) !important;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Sales&Buy</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
      @media only screen and (max-width: 1325px) {
        .container {
          width: 100%; /* Responsive */
        }
      }
    </style>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>

    <%= render 'shared/message' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render partial: 'layouts/footer' %>

  </body>
</html>